language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.4.3
    - DJANGO=1.3.5
    - DJANGO=1.5.0
install:
    - pip install argparse --use-mirrors
    - pip install -q Django==$DJANGO --use-mirrors
script: python quicktest.py helpdesk
